//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;
@protocol FBSDKLogging;

@protocol __FBSDKLoggerCreating
- (id <FBSDKLogging>)createLoggerWithLoggingBehavior:(NSString *)arg1;
@end

