//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBSDKGraphRequestConnecting-Protocol.h"

@class NSMutableArray;

@protocol _FBSDKGraphRequestConnecting <FBSDKGraphRequestConnecting>
@property(readonly, nonatomic) NSMutableArray *requests;
@end

