//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSString;

@protocol _FBSDKLoginEventLogging
- (void)flush;
- (void)logInternalEvent:(NSString *)arg1 parameters:(NSDictionary *)arg2 isImplicitlyLogged:(_Bool)arg3;
@property(nonatomic, readonly) unsigned long long flushBehavior;
@end

